### ISSUE TITLE
 REVIEW Week 12

### ISSUE THREAD

**Issue by wayne-tsai** [SOA-GOAT/SECond-api#2]
#1  is our HW this week.

**Comment by chinyakao** [comment]
It seems that you all upload to same git branches. Remeber to create differents branches for each team members and upload to develop branch. After all the work you did, merge the develop branch to main branch.

**Comment by blauwaliu** [comment]
Thank @chinyakao for the reminder.
Our team members push to the same branch because we meet in person to finish the homework together.
We will merge to the develop branch first before merging to the main branch next week.
